# Generated by Django 3.1.5 on 2021-01-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('catagory', models.CharField(max_length=40)),
                ('quantity', models.IntegerField()),
                ('quality', models.CharField(max_length=50)),
                ('room', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
