# Generated by Django 3.1.5 on 2021-01-12 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_remove_record_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='name',
            new_name='namess',
        ),
    ]
